### ISSUE TITLE
agent-client-js: update FindSegments documentation on README

### ISSUE THREAD

**Issue by such** [stratumn/indigo-js#124]
We should document the new `linkHashes` option.

**Comment by conord33** [comment]
Is this any client side validation I need to update?

**Comment by such** [comment]
Nope it's forwarded straight to the store

*Adrien Montfort*
*VP Engineering*
Stratumn SAS, 1 bis Cité Paradis, 75010 Paris, France
+33 6 85 28 38 46 • <+33%206%2020%2047%2060%2029> adrien@stratumn.com •
stratumn.com
We are hiring <https://stratumn.com/careers> • Read about us
<http://blog.stratumn.com> • Twitter <https://twitter.com/stratumnhq>
