### ISSUE TITLE
agent-ui: refresh segments page and left drawer contents disappears

### ISSUE THREAD

**Issue by jeremie-stratumn** [stratumn/indigo-js#214]
I noticed that when refreshing the segments or maps page the left drawer has no content anymore. This is due to https://github.com/stratumn/indigo-js/pull/182 I believe. The AgentsPage is in charge of fetching STALE agents but it is not always mounted, for example when refreshing the segments page it is not.. 

Should create a class `AgentsInitializer` that always renders (not behind a route) null and fetch stale agents on mount.

Now I can go back to my vacations :)

**Comment by t-bast** [comment]
Yep refresh doesn't work at all on most routes...I'm on it, thanks for the hint ;)
