### ISSUE TITLE
agent-ui: make state persistent

### ISSUE THREAD

**Issue by jeremie-stratumn** [stratumn/indigo-js#74]
### Expected behavior
Make the redux state persistent to allow for refresh of the page without loosing agents list. Look into:
https://github.com/rt2zz/redux-persist
https://medium.com/@clrksanford/persist-ence-is-key-using-redux-persist-to-store-your-state-in-localstorage-ac6a000aee63
or
https://egghead.io/lessons/javascript-redux-persisting-the-state-to-the-local-storage

### Current behavior
the state and all the agents are lost when refresh is hit (or when project recompiles, which happens a lot in dev)

**Comment by t-bast** [comment]
Definitely, I was thinking about this and it shouldn't be too hard.
Thanks for creating the card!
